apiVersion: v1
kind: Namespace
metadata:
  name: wallet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: igorovcharenko/ovcharenko-wallet:0.0.4
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://wallet-db:5432/wallet_container_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"

            - name: APP_PORT
              value: "8080"

            - name: HIKARI_MAX_POOL_SIZE
              value: "100"
            - name: HIKARI_MIN_IDLE
              value: "10"
            - name: HIKARI_IDLE_TIMEOUT
              value: "30000"
            - name: HIKARI_CONN_TIMEOUT
              value: "20000"

            - name: TOMCAT_THREADS_MAX
              value: "100"
            - name: TOMCAT_THREADS_MIN_SPARE
              value: "10"
            - name: TOMCAT_ACCEPT_COUNT
              value: "100"
            - name: TOMCAT_CONN_TIMEOUT
              value: "2000"

---

apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: wallet
spec:
  selector:
    app: wallet-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallet-db-pvc
  namespace: wallet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-db
  namespace: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-db
  template:
    metadata:
      labels:
        app: wallet-db
    spec:
      containers:
        - name: wallet-db
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "wallet_container_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: wallet-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: wallet-db-storage
          persistentVolumeClaim:
            claimName: wallet-db-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: wallet-db
  namespace: wallet
spec:
  selector:
    app: wallet-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP