CREATE TABLE wallet (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        wallet_key UUID NOT NULL UNIQUE,
                        balance NUMERIC(19,4) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);